title: Aadi's Website
description: "Class of 2025"
owner_name: Aadi Bhat
github_username: nighthawkcoders
github_repo: "aadi_2025" 
baseurl: "/site"
future: true
remote_theme: jekyll/minima
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/aadibhat09"}
    - { platform: youtube, user_url: "https://www.youtube.com/@Aadi_Bhat" } 
remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
  - navigation/random-links.md
  - navigation/cookie.md
  - navigation/about.md
  # - navigation/blog.md
  # - navigation/search.md
  - navigation/team.md
  - navigation/journey.md
  # - README4YML.md

